[package]
name = "tellme"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs = "5.0"
log = "0.4"
env_logger = "0.10"
openai_api_rust = "0.1.9"